name: 'Build & Deploy'

concurrency:
  group: prod_deploy
  cancel-in-progress: false

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set execute changeset
        id: changeset
        run: echo "::set-output name=executechangeset::$EXECUTE_CHANGESET"
        env:
          EXECUTE_CHANGESET: ${{ github.event_name == 'repository_dispatch' }}
      - uses: ./
        name: Deploy Static Site
        with:
          outDir: './out'
          token: ${{ secrets.GITHUB_TOKEN }}
          lambdaVersion: '1.0.6'
          executeStackChangeSet: ${{ steps.changeset.outputs.executechangeset }}
          cfStackName: 'static-example-richardwillis-cloudformation-stack'
          s3BucketName: 'static-example-richardwillis-info-us-east-1'
          s3AllowedOrigins: 'https://static-example.richardwillis.info, https://*.preview.static-example.richardwillis.info'
          rootCloudFrontHosts: 'static-example.richardwillis.info'
          previewCloudFrontHosts: '*.preview.static-example.richardwillis.info'
          previewUrlHost: 'preview.static-example.richardwillis.info'
          cacheCorsPathPattern: '/_next/*'
          certificateARN: 'arn:aws:acm:us-east-1:008215002370:certificate/39df7626-7d2f-42e9-94f4-a3ce61ca3d5e'
          removeExtensionFromHtmlFiles: true
