name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cfStackName: 'example-com-static-cloudformation-stack'
          # s3BucketName: 'example.com-us-east-1'
          # s3AllowedOrigins: 'https://example.com, https://*.preview.example.com'
          # rootCloudFrontHosts: 'example.com'
          # previewCloudFrontHosts: '*.preview.example.com'
          # cacheCorsPathPattern: '/_next/*'
          # certificateARN: 'arn:aws:acm:us-east-1:1234567:certificate/123abc-123abc-1234-5678-abcdef'
